import type { Metadata } from "next";
import "./globals.css";
import favicon from "@/public/favicon.png";
import { Archivo, Space_Grotesk } from "next/font/google";

const archivo = Archivo({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--archivo",
});

const spaceGrotesk = Space_Grotesk({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-space-grotesk",
});

export const metadata: Metadata = {
  title: "DoraEbag",
  icons: favicon.src,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} ${archivo.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
